# Generated by Django 5.2.5 on 2025-10-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('np', models.CharField(max_length=45)),
                ('clas', models.CharField(max_length=12)),
            ],
        ),
    ]
