# Generated by Django 5.2.5 on 2025-10-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fgo',
            old_name='clas',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='fgo',
            name='image',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
